### ISSUE TITLE
Add title and description to the chapter

### ISSUE THREAD

**Issue by albertattard** [sociable-weaver/backlog#18]
The chapter contains a collection of entries.  The first entry is usually the chapter entry where we have the chapter's title.  This can be moved outside as each chapter will have a title and a description and these will always be the first two entries.

## Tasks

- [ ] Add the title and the description as properties to the chapter object
- [ ] Render chapter title using the property instead of the entry
- [ ] Remove the chapter entry support
