### ISSUE TITLE
Show all variables on the side of the page

### ISSUE THREAD

**Issue by albertattard** [sociable-weaver/backlog#19]
The content may have many variables and it is ideal to have these visible all the times, as shown next.

![Variables](https://user-images.githubusercontent.com/3372288/146073679-9540a938-5ea4-4b6b-8fb3-4358687bec6b.png)

## Tasks

- [ ] Render all variables on a side panel
- [ ] Make this panel always visible even when the page is scrolled
- [ ] Allow the user to input the variables from the panel too
