### ISSUE TITLE
Allow user to edit the content

### ISSUE THREAD

**Issue by albertattard** [sociable-weaver/backlog#20]
Allow the users (authors and readers) to edit exiting content.

## Tasks

- [x] Proved means to switch to edit mode
- [x] Allow the user to cancel the edit and return to previous state (viewing)
- [x] Allow the user to save the changes made return to previous state (viewing)
  The changes should be saved in the file and the file format should be maintained

**Comment by albertattard** [comment]
Apply this to all entry types.

## Tasks

- [ ] Chapter
- [ ] Command
- [ ] Create
- [ ] Docker Tag and Push
- [ ] Download
- [ ] Git Apply Patch
- [ ] Git Commit Changes
- [ ] Git Tag Current Commit
- [ ] Markdown
- [ ] Replace
- [ ] Section
- [ ] Subsection
- [ ] Variable
